#BOARD=uno

#LIBRARIES := Servo

#include /amaroq/share/Arduino/arduino.mk
#include /u/local/Arduino/arduino.mk

#LIBRARIES := Servo

USER_LIB_PATH = /u/local/Arduino/libraries/

BOARD_TAG=uno

ARDUINO_LIBS = Servo
MONITOR_PORT = /dev/ttyACM0

include /usr/share/arduino/Arduino.mk

