BOARD_TAG=promicro-16MHzatmega32U4
BOARD_TAG=promicro
VARIENT=16MHzatmega32U4
ALTERNATE_CORE = SparkFun
ALTERNATE_CORE_PATH = /home/ryan/.arduino15/packages/SparkFun/hardware/avr/1.1.13/

include /usr/share/arduino/Arduino.mk

